### ISSUE TITLE
/locales/dev.json não encontrado

### ISSUE THREAD

**Issue by ptopenweb** [novosga/painel-web#10]
Aparece o erro
/painel-web/locales/dev.json 404 (Not Found)

Penso que é o fallbak do i18n: fallbackLng:["dev"]

Funciona, com o idioma que coloco por isso não sei porque aparece esse erro.

**Comment by juanzapatac** [comment]
Hello.
I been trying to use with yarn run dev or NPM run dev with no success. Simply white page result.

Any helpt with it?

triagem and novosga works ok.

Regards,

Juan
