### ISSUE TITLE
Tamanhos css vw/vh

### ISSUE THREAD

**Issue by ptopenweb** [novosga/painel-web#11]
Nem todos os browsers suportam tamanhos css vw/vh. http://caniuse.com/#feat=viewport-units
https://github.com/novosga/painel-web/blob/master/themes/default/style.css

Testei numa SmartTV Samsung e as letras ficam muito pequenas.

Que tal ter um tema com maior suporte a SmartTVs e outros browsers mais antigos que utilize "em"? 
Ou então ter um fallback no css do tema principal.

**Comment by rogeriolino** [comment]
Os arquivos CSS mais antigos usam ```em``` ao invés de ```viewport```, mas é muito custoso manter um tema correto nas mais diversas resoluções usando ```em```/```px```.

Então por questão de facilitar a manutenção dos temas foi adotado o ```viewport```, mesmo não sendo implementado na maioria dos navegadores (mas que será implementada futuramente).
