### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by juanzapatac** [novosga/painel-web#13]
Good morning.
I´m using:
w1064/wamp64/php 7.1.11/mysql 5.7.14
npm -v: 5.6.0

I did:
**git clone https://github.com/novosga/painel-web.git**
**cd paninel-web**
**npm install**
  npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please 
     update to babel-preset-minify
  npm notice created a lockfile as package-lock.json. You should commit this file.
  npm WARN painel-web@2.0.0 No repository field.
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.2.0 (node_modules\7zip-
     bin-linux):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-
    linux@1.2.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-
    bin-mac):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: 
    wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: 
    wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

  added 1316 packages in 117.877s

**npm run dev**
Show a blank page and console errors:
C:\wamp64\www\painel-web\node_modules\vuex-i18n\dist\vuex-i18n.es.js:755 
Uncaught SyntaxError: Unexpected token export
at createScript (VM136 vm.js:53)
at Object.runInThisContext (VM136 vm.js:95)
at Module._compile (VM134 module.js:543)
at Object.Module._extensions..js (VM134 module.js:580)
at Module.load (VM134 module.js:488)
at tryModuleLoad (VM134 module.js:447)
at Function.Module._load (VM134 module.js:439)
at Module.require (VM134 module.js:498)
  
If I download and install w64 compiled version, works ok, but I want to make changes to default version.

Any help with this issue?

Regards,

Juan

**Comment by wdtamagi** [comment]
Hello @juanzapatac ,
I recieve this error to, but i tried with yarn and its works like a charm.
If could you try:
`yarn`
and after
`yarn dev`

**Comment by juanzapatac** [comment]
Gracias @wdtamagi works good with Yarn.

**Comment by rogeriolino** [comment]
I dont know why with `npm` doesnt works.

I'm using `yarn` to development but the project README is showing `npm` commands. I'll change the README to use `yarn`.
